name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 9.x, 10.x, 11.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.8
    - run: npm ci
    - run: npm test
    - run: npm run lint
    - run: npm run cs-check
    - run: npm run dist
    - run: pip install mkdocs==1.0.4
    - run: mkdocs build --clean
      env:
        CI: true
      
